<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQDhcALn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQDhcALn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQDhcALn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQDhcALn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQDhcALn\App_KernelDevDebugContainer([
    'container.build_hash' => 'QDhcALn',
    'container.build_id' => '743c4186',
    'container.build_time' => 1606325209,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQDhcALn');
